### ISSUE TITLE
"Var" and "VString" symbolic links are broken

### ISSUE THREAD

**Issue by formix** [Megatokio/Libraries#1]
When cloning Libraries: 
- Var points to the missing directory "../Projects/vipsi/Source/Var/"
- VString points to the missing directory "../Projects/vipsi/Source/VString/"

I don't know yet if this is relevant to the project compilation but I'll give it a shot soon.

**Comment by andlabs** [comment]
It doesn't affect zasm, but it will affect vipsi, if kio ever converts that to a github repository (since their cgit repository is outdated). I was interested in building a local copy of the zasm documentation, but that requires vipsi too, hmmmm

**Comment by Megatokio** [comment]
hi@all,
yes, these links are only required for project 'vipsi' and can be ignored.
This project is already on GitHub, but marked private. I didn't think of someone needing it to create the documentation. I'll work on this.
unfortunately i missed this issue and was only alerted by the new comment. 
happy easter (as happy as can be currently),
kio!

**Comment by Megatokio** [comment]
FYI: i checked and made project 'vipsi' public.
