### ISSUE TITLE
Won't compile on aarm64v8

### ISSUE THREAD

**Issue by bferguson3** [Megatokio/Libraries#5]
In file included from Libraries/kio/auto_config.h:34,
                 from Libraries/kio/kio.h:55,
                 from Libraries/cstrings/cstrings.cpp:19:
Libraries/kio/detect_configuration.h:300:4: error: #error "can't detect processor"
   #error "can't detect processor"
    ^~~~~
In file included from Libraries/kio/auto_config.h:34,
                 from Libraries/kio/kio.h:55,
                 from Libraries/cstrings/cstrings.cpp:19:
Libraries/kio/detect_configuration.h:386:33: error: ‘_sizeof_char’ was not declared in this scope
 static_assert(sizeof(char)   == _sizeof_char,    "Size is not correct");
                                 ^~~~~~~~~~~~
Libraries/kio/detect_configuration.h:387:33: error: ‘_sizeof_short’ was not declared in this scope
 static_assert(sizeof(short)  == _sizeof_short,   "Size is not correct");

**Comment by Megatokio** [comment]
hi, 
checkout branch aarch64 in Libraries/ and try to compile again.
please tell me whether it works or whether some sizeof's are wrong. i can't test it for myself.

**Comment by bferguson3** [comment]
Yep that worked!

One step closer to getting gendev working on pi 400. Thanks.
